---
version: 2
sources:
- name: "hive_metastore.unique_latest"
  database: "hive_metastore"
  schema: "unique_latest"
  config:
    enabled: true
  tables:
  - name: "parquet_all"
    description: "Comprehensive dataset capturing various data types and structures,\
      \ enabling detailed analysis across multiple dimensions."
    columns:
    - name: "c_short"
      description: "A small integer value representing a specific metric."
      dataType:
        type: "SmallInt"
    - name: "c_int"
      description: "An integer value used for various calculations."
      dataType:
        type: "Integer"
    - name: "c_long"
      description: "A large integer value for extensive numerical data."
      dataType:
        type: "Bigint"
    - name: "c_decimal"
      description: "A decimal value representing precise numerical data"
      dataType:
        type: "Decimal"
    - name: "c_float"
      description: "A floating-point number for representing approximate values"
      dataType:
        type: "Float"
    - name: "c_boolean"
      description: "A true/false value indicating a binary state"
      dataType:
        type: "Boolean"
    - name: "c_double"
      description: "A double-precision floating-point number for precise calculations."
      dataType:
        type: "Double"
    - name: "c_string"
      description: "A string of text representing various information."
      dataType:
        type: "String"
    - name: "c_date"
      description: "A date value indicating a specific day."
      dataType:
        type: "Date"
    - name: "c_timestamp"
      description: "Timestamp indicating a specific point in time"
      dataType:
        type: "Timestamp"
    - name: "c_array_int"
      description: "Array of integer values"
      dataType:
        type: "Array"
        dataType:
          type: "Integer"
    - name: "c_array_string"
      description: "Array of string values"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "c_array_long"
      description: "Array of long integer values"
      dataType:
        type: "Array"
        dataType:
          type: "Bigint"
    - name: "c_array_boolean"
      description: "Array of boolean values"
      dataType:
        type: "Array"
        dataType:
          type: "Boolean"
    - name: "c_array_date"
      description: "Array of date values"
      dataType:
        type: "Array"
        dataType:
          type: "Date"
    - name: "c_array_timestamp"
      description: "Array of timestamp values"
      dataType:
        type: "Array"
        dataType:
          type: "Timestamp"
    - name: "c_array_float"
      description: "Array of float values"
      dataType:
        type: "Array"
        dataType:
          type: "Float"
    - name: "c_array_decimal"
      description: "Array of decimal values"
      dataType:
        type: "Array"
        dataType:
          type: "Decimal"
    - name: "c_struct"
      description: "A structured data type containing multiple related fields."
      dataType:
        type: "Struct"
        fields:
        - name: "c_short"
          dataType:
            type: "SmallInt"
          description: "A short integer value within the structured data."
        - name: "c_int"
          dataType:
            type: "Integer"
          description: "An integer value within the structured data."
        - name: "c_long"
          dataType:
            type: "Bigint"
          description: "Long integer value within the structured data"
        - name: "c_decimal"
          dataType:
            type: "Decimal"
          description: "Decimal value within the structured data"
        - name: "c_float"
          dataType:
            type: "Float"
          description: "Floating-point value within the structured data"
        - name: "c_boolean"
          dataType:
            type: "Boolean"
          description: "Boolean value indicating a specific condition within the structure"
        - name: "c_double"
          dataType:
            type: "Double"
          description: "Double precision number representing a measurement within\
            \ the structure"
        - name: "c_string"
          dataType:
            type: "String"
          description: "String value containing descriptive information within the\
            \ structure"
        - name: "c_date"
          dataType:
            type: "Date"
          description: "Date value within the structured data"
        - name: "c_timestamp"
          dataType:
            type: "Timestamp"
          description: "Timestamp value within the structured data"
        - name: "c_array_int"
          dataType:
            type: "Array"
            dataType:
              type: "Integer"
          description: "Array of integer values within the structured data"
    - name: "_rescued_data"
      description: "Data that was rescued during processing, typically containing\
        \ errors or anomalies."
      dataType:
        type: "String"
