name: dbt_sql
description: ''
version: '12'
author: sony@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/databricks_sql_1:
    name: databricks_sql_1
    description: ''
    fabricUID: 8630
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: prophecy_internal_jobs
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2024-10-29 15:15:56'
    author: sony@prophecy.io
    models:
    - 35638/.prophecy/metadata/sqlmodels/seedusage
    sqlProjects: []
  jobs/airflow_sql_1:
    name: airflow_sql_1
    description: ''
    fabricUID: 2745
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2024-10-29 15:17:07'
    author: sony@prophecy.io
    models: []
    sqlProjects:
    - '35638'
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-10-29 14:59:01'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/mtest_1_latest:
    name: mtest_1_latest
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: Segment
        dataType:
          type: String
      - name: Country
        dataType:
          type: String
      - name: Product
        dataType:
          type: String
      - name: Discount_Band
        dataType:
          type: String
      - name: Units_Sold
        dataType:
          type: Double
      - name: Manufacturing_Price
        dataType:
          type: Double
      - name: Sale_Price
        dataType:
          type: Double
      - name: Gross_Sales
        dataType:
          type: Double
      - name: Discounts
        dataType:
          type: String
      - name: Sales
        dataType:
          type: Double
      - name: COGS
        dataType:
          type: Double
      - name: Profit
        dataType:
          type: String
      - name: Date
        dataType:
          type: String
      - name: Month_Number
        dataType:
          type: Double
      - name: Month_Name
        dataType:
          type: String
      - name: Year
        dataType:
          type: Double
      - name: _rescued_data
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - models/mtest_1_latest.sql
    - .prophecy/ide/models/mtest_1_latest.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-10-29 14:59:36'
  .prophecy/metadata/sqlmodels/seedusage:
    name: seedusage
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: name_updated
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - models/seedusage.sql
    - .prophecy/ide/models/seedusage.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-10-29 15:04:19'
sqlSnapshots: {}
sqlTests:
  .prophecy/metadata/sqltests/generic_test:
    name: generic_test
    description: null
    author: sony@prophecy.io
    files:
    - tests/generic_test.sql
    - .prophecy/ide/tests/data/singular/generic_test.json
    testType: SingularDataTest
    createdAt: '2024-10-29 15:10:06'
sqlMacros:
  .prophecy/metadata/sqlmacros/func_1:
    name: func_1
    macroType: expression
    description: null
    author: sony@prophecy.io
    files:
    - macros/func_1.sql
    - .prophecy/ide/macros/func_1.json
    - macros/macros.yml
    createdAt: '2024-10-29 15:04:37'
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: sony@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2024-10-29 14:59:10'
sqlSeeds:
  .prophecy/metadata/sqlseeds/checkseed:
    name: checkseed
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: name
        dataType:
          type: String
      - name: age
        dataType:
          type: Integer
    description: null
    author: sony@prophecy.io
    files:
    - seeds/checkseed.csv
    createdAt: '2024-10-29 15:02:50'
sqlSources:
  .prophecy/metadata/sqlsources/hive_metastore_unique_latest:
    name: hive_metastore.unique_latest
    description: null
    author: sony@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-10-29 14:59:51'
    tables:
    - name: alias_updated
      schema:
        entityType: ''
        providerType: databricks
        fields:
        - name: Segment
          dataType:
            type: String
        - name: Country
          dataType:
            type: String
        - name: Product
          dataType:
            type: String
        - name: Discount_Band
          dataType:
            type: String
        - name: Units_Sold
          dataType:
            type: Double
        - name: Manufacturing_Price
          dataType:
            type: Double
        - name: Sale_Price
          dataType:
            type: Double
        - name: Gross_Sales
          dataType:
            type: Double
        - name: Discounts
          dataType:
            type: String
        - name: Sales
          dataType:
            type: Double
        - name: COGS
          dataType:
            type: Double
        - name: Profit
          dataType:
            type: String
        - name: Date
          dataType:
            type: String
        - name: Month_Number
          dataType:
            type: Double
        - name: Month_Name
          dataType:
            type: String
        - name: Year
          dataType:
            type: Double
        - name: _rescued_data
          dataType:
            type: String
      description: Sales performance data encompassing costs, profits, pricing, and
        sales metrics, aiding in financial analysis and decision-making.
      author: sony@prophecy.io
      createdAt: '2024-10-29 14:59:51'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: sony@prophecy.io
  createdAt: '2024-10-29 14:59:01'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
