---
version: 2
snapshots:
- name: "newtest_check"
  columns:
  - name: "C_INT"
    dataType:
      type: "Number"
  - name: "C_STRING"
    dataType:
      type: "Boolean"
  - name: "C_TIMESTAMP"
    dataType:
      type: "Timestamp"
  - name: "C_INT1"
    dataType:
      type: "String"
  - name: "C_AVG"
    dataType:
      type: "Number"
  - name: "SERVICE_LABEL_1"
    dataType:
      type: "String"
  - name: "C_ARRAY_INT"
    dataType:
      type: "Array"
  - name: "DBT_SCD_ID"
    dataType:
      type: "String"
  - name: "DBT_UPDATED_AT"
    dataType:
      type: "String"
  - name: "DBT_VALID_FROM"
    dataType:
      type: "String"
  - name: "DBT_VALID_TO"
    dataType:
      type: "String"
  tests: []
- name: "k1"
  columns:
  - name: "C_NUM"
    dataType:
      type: "Number"
  - name: "C_NUM10"
    dataType:
      type: "Number"
  - name: "C_DEC"
    dataType:
      type: "Number"
  - name: "C_NUMERIC"
    dataType:
      type: "Number"
  - name: "C_INT"
    dataType:
      type: "Number"
  - name: "C_INTEGER"
    dataType:
      type: "Number"
  - name: "C_DOUBLE"
    dataType:
      type: "Float"
  - name: "C_FLOAT"
    dataType:
      type: "Float"
  - name: "C_COUBLE_PRECISION"
    dataType:
      type: "Float"
  - name: "C_REAL"
    dataType:
      type: "Float"
  - name: "C_VARCHAR"
    dataType:
      type: "String"
  - name: "C_VARCHAR50"
    dataType:
      type: "String"
  - name: "C_CHAR"
    dataType:
      type: "String"
  - name: "C_CHAR10"
    dataType:
      type: "String"
  - name: "C_STRING"
    dataType:
      type: "String"
  - name: "C_STRING20"
    dataType:
      type: "String"
  - name: "C_TEXT"
    dataType:
      type: "String"
  - name: "C_TEXT30"
    dataType:
      type: "String"
  - name: "C_BINARY"
    dataType:
      type: "Binary"
  - name: "C_BINARY100"
    dataType:
      type: "Binary"
  - name: "C_VARBINARY"
    dataType:
      type: "Binary"
  - name: "C_BOOL"
    dataType:
      type: "Boolean"
  - name: "C_TIMESTAMP"
    dataType:
      type: "Timestamp"
  - name: "C_DATE"
    dataType:
      type: "Date"
  - name: "C_DATETIME"
    dataType:
      type: "Timestamp"
  - name: "C_TIME"
    dataType:
      type: "Time"
  - name: "C_TIMESTAMPLTZ"
    dataType:
      type: "Timestamp"
  - name: "C_TIMESTAMP_NTZ"
    dataType:
      type: "Timestamp"
  - name: "C_VARIANT"
    dataType:
      type: "Variant"
  - name: "C_ARRAY"
    dataType:
      type: "Array"
  - name: "C_OBJECT"
    dataType:
      type: "Object"
  - name: "C_GEOGRAPHY"
    dataType:
      type: "Geography"
  - name: "DBT_SCD_ID"
    dataType:
      type: "String"
  - name: "DBT_UPDATED_AT"
    dataType:
      type: "Float"
  - name: "DBT_VALID_FROM"
    dataType:
      type: "Float"
  - name: "DBT_VALID_TO"
    dataType:
      type: "Float"
