---
version: 2
sources:
- name: "hive_metastore.unique_latest"
  database: "hive_metastore"
  schema: "unique_latest"
  config:
    enabled: true
  tables:
  - name: "alias_updated"
    description: "Sales performance data encompassing costs, profits, pricing, and\
      \ sales metrics, aiding in financial analysis and decision-making."
    columns:
    - name: "Segment"
      description: "The market segment to which the product belongs"
      dataType:
        type: "String"
    - name: "Country"
      description: "The country where the product was sold"
      dataType:
        type: "String"
    - name: "Product"
      description: "The name of the product sold"
      dataType:
        type: "String"
    - name: "Discount_Band"
      description: "Category of discount applied to the product"
      dataType:
        type: "String"
    - name: "Units_Sold"
      description: "Total number of units sold for the product"
      dataType:
        type: "Double"
    - name: "Manufacturing_Price"
      description: "The cost incurred to manufacture the product"
      dataType:
        type: "Double"
    - name: "Sale_Price"
      description: "The price at which the product is sold to customers"
      dataType:
        type: "Double"
    - name: "Gross_Sales"
      description: "Total revenue generated from sales before any discounts are applied"
      dataType:
        type: "Double"
    - name: "Discounts"
      description: "Details of discounts applied to sales"
      dataType:
        type: "String"
    - name: "Sales"
      description: "Total revenue generated from sales transactions."
      dataType:
        type: "Double"
    - name: "COGS"
      description: "Cost of goods sold, representing the direct costs attributable\
        \ to the production of the sold goods."
      dataType:
        type: "Double"
    - name: "Profit"
      description: "The profit generated from sales after deducting costs"
      dataType:
        type: "String"
    - name: "Date"
      description: "The date when the sales transaction occurred"
      dataType:
        type: "String"
    - name: "Month_Number"
      description: "Numeric representation of the month in which sales occurred"
      dataType:
        type: "Double"
    - name: "Month_Name"
      description: "Name of the month in which the sales occurred"
      dataType:
        type: "String"
    - name: "Year"
      description: "The year in which the sales data was recorded"
      dataType:
        type: "Double"
    - name: "_rescued_data"
      description: "Information about data that was recovered or salvaged"
      dataType:
        type: "String"
  - name: "parquet_all"
    description: "Comprehensive dataset capturing various data types and structures,\
      \ enabling detailed analysis across multiple dimensions."
    columns:
    - name: "c_short"
      description: "A small integer value representing a specific metric."
      dataType:
        type: "SmallInt"
    - name: "c_int"
      description: "An integer value used for various calculations."
      dataType:
        type: "Integer"
    - name: "c_long"
      description: "A large integer value for extensive numerical data."
      dataType:
        type: "Bigint"
    - name: "c_decimal"
      description: "A decimal value representing precise numerical data"
      dataType:
        type: "Decimal"
    - name: "c_float"
      description: "A floating-point number for representing approximate values"
      dataType:
        type: "Float"
    - name: "c_boolean"
      description: "A true or false value indicating a binary state"
      dataType:
        type: "Boolean"
    - name: "c_double"
      description: "A double-precision floating-point number for precise calculations."
      dataType:
        type: "Double"
    - name: "c_string"
      description: "A string of text representing various information."
      dataType:
        type: "String"
    - name: "c_date"
      description: "A date value indicating a specific day."
      dataType:
        type: "Date"
    - name: "c_timestamp"
      description: "Timestamp indicating a specific moment in time"
      dataType:
        type: "Timestamp"
    - name: "c_array_int"
      description: "Array of integer values"
      dataType:
        type: "Array"
        dataType:
          type: "Integer"
    - name: "c_array_string"
      description: "Array of string values"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "c_array_long"
      description: "Array of long integer values"
      dataType:
        type: "Array"
        dataType:
          type: "Bigint"
    - name: "c_array_boolean"
      description: "Array of boolean values"
      dataType:
        type: "Array"
        dataType:
          type: "Boolean"
    - name: "c_array_date"
      description: "Array of date values"
      dataType:
        type: "Array"
        dataType:
          type: "Date"
    - name: "c_array_timestamp"
      description: "Array of timestamp values"
      dataType:
        type: "Array"
        dataType:
          type: "Timestamp"
    - name: "c_array_float"
      description: "Array of float values"
      dataType:
        type: "Array"
        dataType:
          type: "Float"
    - name: "c_array_decimal"
      description: "Array of decimal values"
      dataType:
        type: "Array"
        dataType:
          type: "Decimal"
    - name: "c_struct"
      description: "A structured data type containing multiple related fields."
      dataType:
        type: "Struct"
        fields:
        - name: "c_short"
          dataType:
            type: "SmallInt"
          description: "A short integer value within the structured data."
        - name: "c_int"
          dataType:
            type: "Integer"
          description: "An integer value within the structured data."
        - name: "c_long"
          dataType:
            type: "Bigint"
          description: "Long integer value within the structured data"
        - name: "c_decimal"
          dataType:
            type: "Decimal"
          description: "Decimal value within the structured data"
        - name: "c_float"
          dataType:
            type: "Float"
          description: "Floating-point value within the structured data"
        - name: "c_boolean"
          dataType:
            type: "Boolean"
          description: "Boolean value indicating a specific condition within the structured\
            \ data"
        - name: "c_double"
          dataType:
            type: "Double"
          description: "Double precision value representing a measurement within the\
            \ structured data"
        - name: "c_string"
          dataType:
            type: "String"
          description: "String value containing descriptive information within the\
            \ structured data"
        - name: "c_date"
          dataType:
            type: "Date"
          description: "Date value within the structured data"
        - name: "c_timestamp"
          dataType:
            type: "Timestamp"
          description: "Timestamp value within the structured data"
        - name: "c_array_int"
          dataType:
            type: "Array"
            dataType:
              type: "Integer"
          description: "Array of integer values within the structured data"
    - name: "_rescued_data"
      description: "String containing data that was rescued during processing"
      dataType:
        type: "String"
