# ==================
# Project Details
# ==================
name: "snow_datatest"
config-version: 2
require-dbt-version:
- ">=1.0.0"
- "<2.0.0"
version: "0.1"
profile: "prophecy-default"

# ==================
# File Path Configs
# ==================
clean-targets:
- "target"
- "dbt_modules"
- "logs"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  qa_config: "qa"
  qa_schema: "qa_schema"
  schema_qa_db_warehouse: "qa_db_warehouse"
  v_project_dict: "{'a': 2, 'b': 'hello'}"
  v_project_int: "20"
  v_project_int_real: 20
  v_project_string_real: "projectstring"

# ==================
# Model Configs
# ==================
models: null
