name: sql_ext_db
description: ''
version: '2'
author: sony@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/sg_db:
    name: sg_db
    description: ''
    fabricUID: 2522
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-08-30 06:30:41'
    author: sony@prophecy.io
    models: []
    sqlProjects:
    - '14119'
  jobs/sg_db_1:
    name: sg_db_1
    description: ''
    fabricUID: 2522
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-08-30 06:40:10'
    author: sony@prophecy.io
    models:
    - mod123
    sqlProjects: []
  jobs/air_job:
    name: air_job
    description: ''
    fabricUID: 735
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: true
    createdAt: '2024-08-30 06:49:08'
    author: sony@prophecy.io
    models: []
    sqlProjects:
    - '14119'
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-08-30 06:25:05'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/mod123:
    name: mod123
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: Segment
        dataType:
          type: String
      - name: Country
        dataType:
          type: String
      - name: Product
        dataType:
          type: String
      - name: Discount_Band
        dataType:
          type: String
      - name: Units_Sold
        dataType:
          type: Float
      - name: Manufacturing_Price
        dataType:
          type: Float
      - name: Sale_Price
        dataType:
          type: Float
      - name: Gross_Sales
        dataType:
          type: Float
      - name: Discounts
        dataType:
          type: String
      - name: Sales
        dataType:
          type: Float
      - name: COGS
        dataType:
          type: Float
      - name: Profit
        dataType:
          type: String
      - name: Date
        dataType:
          type: String
      - name: Month_Number
        dataType:
          type: Float
      - name: Month_Name
        dataType:
          type: String
      - name: Year
        dataType:
          type: Float
      - name: _rescued_data
        dataType:
          type: String
    description: null
    author: sony@prophecy.io
    files:
    - models/mod123.sql
    - .prophecy/ide/models/mod123.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-08-30 06:29:34'
sqlSnapshots: {}
sqlTests: {}
sqlMacros:
  .prophecy/metadata/sqlmacros/generate_schema_name:
    name: generate_schema_name
    macroType: expression
    description: null
    author: sony@prophecy.io
    files:
    - macros/generate_schema_name.sql
    - .prophecy/ide/macros/generate_schema_name.json
    createdAt: '2024-08-30 06:25:13'
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/hive_metastore_unique_latest:
    name: hive_metastore.unique_latest
    description: null
    author: sony@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-08-30 06:29:48'
    tables:
    - name: segment_country_1
      schema:
        entityType: ''
        providerType: databricks
        fields:
        - name: Segment
          dataType:
            type: String
        - name: Country
          dataType:
            type: String
        - name: Product
          dataType:
            type: String
        - name: Discount_Band
          dataType:
            type: String
        - name: Units_Sold
          dataType:
            type: Double
        - name: Manufacturing_Price
          dataType:
            type: Double
        - name: Sale_Price
          dataType:
            type: Double
        - name: Gross_Sales
          dataType:
            type: Double
        - name: Discounts
          dataType:
            type: String
        - name: Sales
          dataType:
            type: Double
        - name: COGS
          dataType:
            type: Double
        - name: Profit
          dataType:
            type: String
        - name: Date
          dataType:
            type: String
        - name: Month_Number
          dataType:
            type: Double
        - name: Month_Name
          dataType:
            type: String
        - name: Year
          dataType:
            type: Double
        - name: _rescued_data
          dataType:
            type: String
      description: Sales performance data segmented by country, providing insights
        into pricing, sales volume, and profitability across different products and
        time periods.
      author: sony@prophecy.io
      createdAt: '2024-08-30 06:38:30'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: sony@prophecy.io
  createdAt: '2024-08-30 06:25:05'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
